### ISSUE TITLE
Internal depencencies resolution POC

### ISSUE THREAD

**Issue by sepo27** [sepo27/libj#1]
### Idea
To require internal dependencies from within src use relative paths.
And resolve accordingly when publishing

### Flow
- import dependencies within src using relative paths
- resolve dependencies during pre-publish
  - publish from `dist`
  - run prepare script only for packages being pushed
    - swap relative paths to npm paths
    - update `package.json` respectively

**Comment by sepo27** [comment]
### Test
- [ ] npm install from remote
- [ ] test npm installl from local

**Comment by sepo27** [comment]
### TODOs
- [ ] remove package from package.json when no longer used
